chor (profile): fix deployments bugs
18:45:20.195
src/pages/Profile.tsx(5,1): error TS6133: 'Button' is declared but its value is never read.
18:45:20.198
src/pages/Profile.tsx(10,1): error TS6133: 'Link' is declared but its value is never read.
18:45:20.497
Error: Command "npm run build" exited with 2