fix some deployments bugs
-
src/contexts/authContext.tsx(101,20): error TS6133: 'data' is declared but its value is never read.
- src/pages/NotFound.tsx(5,1): error TS6133: 'Layout' is declared but its value is never read.